config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index" 

  post '/search', to: 'search#search'
  get '/analytics', to: 'analytics#index'
  resources :articles, only: [:new, :create, :show]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :author, class_name: 'User'
end

app/models/global_key_words_analytic.rb
class GlobalKeyWordsAnalytic < ApplicationRecord
    def self.update_previous_day_rank_reset
        records = order(current_day_hit: :desc, updated_at: :desc)
        records.each_with_index do |record, index|
            record.update(previous_day_rank: index+1, previous_day_hit: record.current_day_hit)
        end
        update_all(current_day_hit: 0)
    end

    def self.update_previous_week_rank_reset
        records = order(current_week_hit: :desc, updated_at: :desc)
        records.each_with_index do |record, index|
            record.update(previous_week_rank: index+1, previous_week_hit: record.current_week_hit)
        end
        update_all(current_week_hit: 0)
    end

    def self.update_previous_month_rank_reset
        records = order(current_month_hit: :desc, updated_at: :desc)
        records.each_with_index do |record, index|
            record.update(previous_month_rank: index+1, previous_month_hit: record.current_month_hit)
        end
        update_all(current_month_hit: 0)
    end
end

app/models/search_analytic.rb
class SearchAnalytic < ApplicationRecord
    has_many :search_analytics_dates
end

app/models/search_analytics_date.rb
class SearchAnalyticsDate < ApplicationRecord
  belongs_to :search_analytic
  belongs_to :users, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :validatable

  has_many :search_analytics_dates, foreign_key: 'user_id'
  has_many :search_analytics, through: :search_analytics_dates
  has_many :articles, foreign_key: 'author_id'
  has_many :user_key_words_analytic, foreign_key: 'user_id'

end

app/models/user_key_words_analytic.rb
require 'json'

class UserKeyWordsAnalytic < ApplicationRecord
    belongs_to :users, class_name: 'User'

    def update_keywords(new_keywords)
        existing_keywords = keywords.nil? ? {} : JSON.parse(keywords.gsub('=>', ':'))
        
        new_keywords.each do |keyword,count|
            if(existing_keywords.key?(keyword))
                existing_keywords[keyword] += count
            else
                existing_keywords[keyword] = count
            end
        end
        existing_keywords = existing_keywords.sort_by {|key, value| value}.reverse.to_h # sort keywords to can use it while get top keywords
        self.keywords = existing_keywords.to_json
        self.save
    end
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
    before_action :authenticate_user!
    
    def index
      user = current_user
  
      global_last_day_search_analytics = SearchAnalytic.where(updated_at: 1.day.ago..DateTime.now).order(searched: :desc).limit(10)

      last_week_search_analytics = SearchAnalyticsDate.where(users: user, searched_date: 1.week.ago..Date.today).order(hits: :desc).limit(10)
  
      trending_keywords_previous_day = GlobalKeyWordsAnalytic.order(previous_day_rank: :asc, updated_at: :desc).limit(100)
      trending_keywords_previous_week = GlobalKeyWordsAnalytic.order(previous_week_rank: :asc, updated_at: :desc).limit(100)
      trending_keywords_previous_month = GlobalKeyWordsAnalytic.order(previous_month_rank: :asc, updated_at: :desc).limit(100)


      sum_searched = SearchAnalytic.sum(:searched)
      sum_found = SearchAnalytic.sum(:found)

      render 'analytics', locals: { 
        last_week_search_analytics: last_week_search_analytics,
        global_last_day_search_analytics: global_last_day_search_analytics,
        searched: sum_searched,
        found: sum_found,
        trending_keywords_previous_day: trending_keywords_previous_day,
        trending_keywords_previous_week: trending_keywords_previous_week,
        trending_keywords_previous_month: trending_keywords_previous_month
      }
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
  
    def configure_devise_parameters
      devise_parameter_sanitizer.permit(:sign_up) do |user|
        user.permit(:name, :email, :password, :password_confirmation)
      end
    end
  end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
  
    def new
      @article = Article.new
    end
  
    def create
      @article = current_user.articles.build(article_params)
      if @article.save
        redirect_to root_path, notice: 'Article was successfully created.'
      else
        render :new
      end
    end
  
    def show
      @article = Article.find(params[:id])
    end
    
    private
  
    def article_params
      params.require(:article).permit(:title, :content)
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    recommended_articles = fetch_recommended_articles(current_user)
    render 'index', locals: { recommended_articles: recommended_articles.to_a }
  end
  
  def fetch_recommended_articles(user)
    user_keywords = UserKeyWordsAnalytic.find_or_initialize_by(users: current_user);
    user_keywords_array =user_keywords.keywords.nil? ? {} : JSON.parse(user_keywords.keywords).keys.first(10).shuffle() # shuufle the array to ge random order
    query_array = user_keywords_array.map{|k| "%#{k}%"}
    


    article = Article.where("title ILIKE ANY (ARRAY[?]) OR content ILIKE ANY (ARRAY[?])", 
                  query_array, query_array).limit(10)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    before_action :authenticate_user!

    def search
      query = params[:query]&.strip
      return if query.blank?
      
      @articles = Article.where('title ILIKE ? OR content ILIKE ?', "%#{query}%", "%#{query}%")
      
      if query.include?('?')
        UpdateKeyWordsAnalyticsJob.perform_later({keywords: query_tokenizer(query.downcase), user:current_user})
        UpdateGlobalKeyWordsAnalyticsJob.perform_later({keywords: query_tokenizer(query.downcase)})
        UpdateSearchAnalyticsJob.perform_later({query: query, articles: @articles.to_a, user: current_user})
      end

      render json: { articles: @articles.as_json(include: { author: { only: :name } }) }
    end

    private 
    def query_tokenizer(query)
      tgr = EngTagger.new
      tgr.get_words(query)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/analytics/analytics.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <h1>Analytics</h1>

      <div class="card mb-4">
        <div class="card-body">
          <div class="d-flex flex-row justify-content-between align-items-start">
            <h4 class="card-title">Last Week Search Analytics</h4>
            <div>
              <span class="badge bg-primary rounded-pill mb-2">N.of searched: <%= searched %></span>
              <span class="badge bg-primary rounded-pill mb-2">N.of found result: <%= found %></span>
            </div>
          </div>
          <hr>

          <div class="row">
            <div class="col-md-6">
              <h5 class="card-subtitle mb-2 text-muted">Your top search Last Week</h5>
              <ul class="list-group mb-4">
                <% last_week_search_analytics.each do |search_analytics_date| %>
                  <li class="list-group-item">
                    <%= search_analytics_date.search_analytic.query %> (<%= search_analytics_date.hits %>)
                  </li>
                  <% end %>
              </ul>
            </div>

            <div class="col-md-6">
              <h5 class="card-subtitle mb-2 text-muted">Global Last Day Search Analytics</h5>
              <ul class="list-group mb-4">
                <% global_last_day_search_analytics.each do |search_analytic| %>
                  <li class="list-group-item">
                    <%= search_analytic.query %> (<%= search_analytic.searched %>)
                  </li>
                  <% end %>
              </ul>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <h5 class="card-subtitle mb-2 text-muted">Trending Keywords Previous Day</h5>
              <ul class="list-group mb-4 overflow-auto" style="max-height: 20rem;">
                <% trending_keywords_previous_day.each_with_index do |keyword,index| %>
                  <li class="list-group-item d-flex flex-row justify-content-between align-items-center">
                    <div>
                      <%=index + 1%>) <%= keyword.keyword %>
                    </div>
                    <div class="d-flex flex-column">
                      <span class="badge bg-primary rounded-pill mb-2">N.of previous hits: <%= keyword.previous_day_hit
                          %></span>
                      <span class="badge bg-primary rounded-pill">N.of current hits: <%= keyword.current_day_hit %>
                          </span>
                    </div>
                  </li>
                  <% end %>
              </ul>
            </div>

            <div class="col-md-4">
              <h5 class="card-subtitle mb-2 text-muted">Trending Keywords Previous Week</h5>
              <ul class="list-group mb-4 overflow-auto" style="max-height: 20rem;">
                <% trending_keywords_previous_week.each_with_index do |keyword, index| %>
                  <li class="list-group-item d-flex flex-row justify-content-between align-items-center">
                    <div>
                      <%=index + 1%>) <%= keyword.keyword %>
                    </div>
                    <div class="d-flex flex-column">
                      <span class="badge bg-primary rounded-pill mb-2">N.of previous hits: <%= keyword.previous_week_hit
                          %></span>
                      <span class="badge bg-primary rounded-pill">N.of current hits: <%= keyword.current_week_hit %>
                          </span>
                    </div>
                  </li>
                  <% end %>
              </ul>
            </div>

            <div class="col-md-4">
              <h5 class="card-subtitle mb-2 text-muted">Trending Keywords Previous Month</h5>
              <ul class="list-group mb-4 overflow-auto" style="max-height: 20rem;">
                <% trending_keywords_previous_month.each_with_index do |keyword,index| %>
                  <li class="list-group-item d-flex flex-row justify-content-between align-items-center">
                    <div>
                      <%=index +1 %>) <%= keyword.keyword %>
                    </div>
                    <div class="d-flex flex-column">
                      <span class="badge bg-primary rounded-pill mb-2">N.of previous hits: <%= keyword.previous_month_hit
                          %></span>
                      <span class="badge bg-primary rounded-pill">N.of current hits: <%= keyword.current_month_hit %>
                          </span>
                    </div>
                  </li>
                  <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="d-flex justify-content-center">
        <%= link_to 'Back to home' , '/' , class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<section class="container my-4">
    <h2 class="text-center fs-1 mb-4">Create New Article</h2>
    <%= form_with(model: @article, url: articles_path) do |form| %>
        <div class="form-group">
            <% form.label :title %>
                <%= form.text_field :title, class:"form-control col-6", placeholder:"Enter the Title of the article" %>
        </div>

        <div class="form-group my-4">
            <% form.label :content %>
                <%= form.text_area :content, class:"form-control col-6", rows: 4, placeholder:"Enter the content of the article" %>
        </div>

        <div class="text-center mb-2">
            <%= form.submit 'Create Article' , class: 'btn btn-primary' %>
        </div>
        <% end %>
            <div class="text-center">
                <%= link_to 'Back to home' , '/' , class: "btn btn-primary" %>
            </div>
</section>

app/views/articles/show.html.erb
<div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card border-0 shadow">
          <div class="card-body">
            <h2 class="card-title"><%= @article.title %></h2>
            <p class="card-text"><%= @article.content %></p>
            <div class="text-muted mb-3">
              <small>Published <%= time_ago_in_words(@article.created_at) %> ago</small>
            </div>
            <div class="d-flex justify-content-between align-items-center">
              <div>
                <span class="badge bg-primary"><%= @article.searched_hits %> Hits</span>
                <span class="badge bg-secondary"><%= @article.author.name %></span>
              </div>
              <div>
                <%= link_to 'Back to Home',  '/', class: 'btn btn-secondary' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/home/index.html.erb
<div class="container">

    <div class="row justify-content-center mt-6">
        <div class="col-md-8 ">
            <div class="d-flex flex-row justify-content-between mt-4 align-items-start">
                <h1>Real-Time Search</h1>
                <div class="mt-2">
                    <%= link_to 'Create Article' , new_article_path, class: "btn btn-primary" %>
                        <%= link_to 'Logout' , destroy_user_session_path, data: { turbo_method: :delete },
                            class: "btn btn-outline-danger" %>
                </div>
            </div>
            <form class="d-flex mt-4" id="search-form">
                <input class="form-control me-2" type="search" placeholder="Search articles..." id="search-input">
                <button class="btn btn-outline-success me-2" type="submit" id="search-button">Search</button>
                <%= link_to 'Analytics' , '/analytics' , class: "btn btn-primary" %>
            </form>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-8 mt-4">
            <ul id="search-results" class="list-group border-0">
            </ul>
        </div>
    </div>

</div>

<% if recommended_articles.length> 0 %>
    <div class="container mt-4">
        <h2>Recommended Articles</h2>
        <div class="row">
            <% recommended_articles.each do |article| %>
                <div class="col-md-4">
                    <div class="card mb-4" style="height:14rem;">
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title">
                                <%= article.title %>
                            </h5>
                            <p class="card-text flex-grow-1">
                                <%= article.content.slice(0, 100) %>
                                    <% if article.content.length> 100 %>
                                        ...
                                        <% end %>
                            </p>
                            <p class="card-text text-muted small mt-auto">Author: <%= article.author.name %>
                            </p>
                            <div class="mt-auto">
                                <%= link_to 'Read More',article_path(article) , class: "btn btn-primary" %>
                            </div>
                        </div>
                    </div>
                </div>
                <% end %>
        </div>
    </div>
    <%end%>
        <%= javascript_include_tag 'search' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchEngine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>